#
#  Author:  Zhengqiu Zhang
#  
#  Date: 11/26/2007
#
SHELL = /bin/sh
AR = ar
CP = cp
RM = rm
CD = cd
CC = cc
MKDIR = mkdir
CHMOD = chmod
MAKE = make
#
###################################################################
#

all : 
	${CD} ssib4_src ; ${MAKE} 

ssib4 : 
	${CD} ssib4_src ; ${MAKE}

clean :
	${CD} ssib4_src ; ${MAKE} clean

